language: node_js

os:
  - osx
  - linux

cache:
  directories:
    - node_modules

node_js:
  - "10"
  - "12"
  - "13"
  - "15"
  - "node"

install:
  - yarn install
script:
  - yarn lint
  - yarn build
  - yarn test
