language: node_js

os:
  - osx
  - linux

cache:
  directories:
    - node_modules

node_js:
  - "18"
  - "20"
  - "22"
  - "node"

install:
  - yarn install
script:
  - yarn lint
  - yarn build
  - yarn test
