os: Visual Studio 2022

environment:
  matrix:
    - nodejs_version: "18"
    - nodejs_version: "20"
    - nodejs_version: "22"
    - nodejs_version: "Current"

platform:
  - x64
  - x86

shallow_clone: true

install:
  - ps: Install-Product node $env:nodejs_version $env:Platform
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - npm config get
  - npm install node-gyp
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - npm install

build:
  verbosity: minimal
test_script:
- ps: npm test